# Generated by Django 5.2 on 2025-05-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_remove_receta_insumo_recetainsumo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
