# Generated by Django 5.2 on 2025-05-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta']},
        ),
    ]
